[package]
name = "chaseconv"
version = "0.1.0"
authors = ["Gabriel Faria"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
byteorder = "1.4.3"
glam = "0.18.0"
memchr = "2.4.1"
